name: TabTPS
version: $version
main: xyz.jpenilla.tabtps.paper.TabTPSPlugin
description: $description
authors:
  - jmp
website: $github
api-version: 1.21
folia-supported: true
softdepend:
  - PlaceholderAPI
  - ViaVersion
loadbefore:
  - Essentials
